<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function owlcarousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'entity.owl_carousel_style.collection':
      return '<p>' . t('Lorem ipsum.') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function owlcarousel_theme() {
  return [
    'owlcarousel_wrapper' => [
      'variables' => [
        'items' => [],
        'preset' => NULL,
      ],
    ],
    'owlcarousel_item' => [
      'variables' => [
        'type' => NULL,
      ],
    ],
  ];
}

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * TODO: move the code to a service.
 */
function owlcarousel_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ('owl_carousel_style' === $entity->getEntityTypeId()) {
    /** @var \Drupal\owlcarousel\Entity\OwlCarouselStyle $entity */
    $generalName = $entity->getName() . '_general';

    \Drupal::entityManager()
      ->getStorage('owl_carousel_style_variant')
      ->create([
        'name' => $generalName,
        'label' => \Drupal::translation()->translate('General'),
      ])->save();
    $entity->addVariant($generalName);

    if ($entity->isResponsive()) {
      // todo: create responsive variants
    }
  }
}
