<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function owlcarousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'entity.owl_carousel_style.collection':
      return '<p>' . t('Lorem ipsum.') . '</p>';
  }
}

/**
 * Implements hook_theme()
 */
function owlCarousel_theme(){
  return [
    'owlCarousel_wrapper' => [
      'variables' => [
        'type' => NuLL,
      ],
      'template' => 'owl.wrapper'
    ],
    'owlCarousel_item' => [
      'variables' => [
        'type' => NuLL,
      ],
      'template' => 'owl.item'
    ],
  ];
}
