<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\owlcarousel\Entity\OwlCarouselStyleVariant;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function owlcarousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'entity.owl_carousel_style.collection':
      return '<p>' . t('Lorem ipsum.') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function owlcarousel_theme() {
  return [
    'owlcarousel_wrapper' => [
      'variables' => [
        'items' => [],
        'preset' => NULL,
      ],
    ],
    'owlcarousel_item' => [
      'variables' => [
        'type' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_presave().
 */
function owlcarousel_entity_presave(EntityInterface $entity) {
  if ('owl_carousel_style' === $entity->getEntityTypeId()) {
    /** @var \Drupal\owlcarousel\OwlCarouselManager $owlCarouselManager */
    $owlCarouselManager = \Drupal::service('owlcarousel.manager');
    $owlCarouselManager->generateVariants($entity);
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function owlcarousel_entity_operation_alter(&$operations, $entity) {
  if($entity instanceof OwlCarouselStyleVariant) {
    $owlCarouselStyle = \Drupal::request()->get('owl_carousel_style');

    foreach($operations as $operation) {
      /** @var \Drupal\Core\Url $url_info */
      $url_info = $operation['url'];
      $url_info->setRouteParameter('owl_carousel_style', $owlCarouselStyle);
    }
  }
}

/**
 * Implements hook_preprocess_views_view_owlcarousel().
 */
function owlcarousel_preprocess_views_view_owlcarousel(&$variables) {
  $variables['#attached']['library'][] = 'owlcarousel/owlsettings';
}
