# Schema for configuration files of the Owl Carousel module.

owlcarousel.owlcarousel.*:
  type: config_entity
  label: 'Owl carousel style'
  mapping:
    name:
      type: string
    label:
      type: label
      label: 'Label'
    items:
      type: integer
      label: 'Items'
    variants:
      type: sequence
      label: 'Variants'
      sequence:
        - type: owl_carousel_style_variant
          label: 'Variant'
